--[[
LuCI - Lua Configuration Interface
Version definition - do not edit this file
]]--

module "luci.version"

distname    = "Pulsar Gateway"
distversion = "LTS 17"

luciname    = "LuCI"
luciversion = "0.12"
