#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=40
STOP=98

system_config() {
	local cfg="$1"

	local hostname conloglevel

	config_get hostname "$cfg" hostname 'WR-IntelligentDevice'
	echo "$hostname" > /proc/sys/kernel/hostname

	config_get conloglevel "$cfg" conloglevel
	config_get buffersize "$cfg" buffersize
	[ -z "$conloglevel" -a -z "$buffersize" ] || dmesg ${conloglevel:+-n $conloglevel} ${buffersize:+-s $buffersize}

	config_get zonename "$cfg" zonename
	[ -n "$zonename" ] && [ -f "/usr/share/zoneinfo/$zonename" ] && ln -sf "/usr/share/zoneinfo/$zonename" /etc/localtime
}

apply_uci_config() {
	sh -c '. /lib/functions.sh; include /lib/config; uci_apply_defaults'
}

scan_hardwares() {
        # detect 3G modem and sim card
	/lib/network/detect-modem.py
}

start() {
	[ -f /proc/net/vlan/config ] && vconfig set_name_type DEV_PLUS_VID_NO_PAD

	rm -rf /var/volatile/state >/dev/null 2>&1
	rm /var/state >/dev/null 2>&1
	mkdir -p /var/volatile/state
	cd /var
	ln -sf volatile/state state
	mkdir -p /tmp/.uci
	chmod 0700 /tmp/.uci
	touch /var/log/wtmp
	touch /var/log/lastlog
	touch /tmp/resolv.conf.auto
	ln -sf /tmp/resolv.conf.auto /tmp/resolv.conf

	load_modules /etc/modules.d/*

	# allow wifi modules time to settle
	sleep 1

	#restore the last booting generated wifi config file
	[ -f /etc/config/wireless ] && {
		mv /etc/config/wireless /etc/config/old-wireless
	}

	/sbin/wifi detect > /tmp/wireless.tmp
	[ -s /tmp/wireless.tmp ] && {
		[ -f /etc/config/old-wireless ] && {
			mv /etc/config/old-wireless /etc/config/wireless
		} || {
			cat /tmp/wireless.tmp >> /etc/config/wireless
		}
		chmod 0600 /etc/config/wireless
	}
	rm -f /tmp/wireless.tmp

	#delete the last booting generated wifi config file
	[ -f /etc/config/old-wireless ] && {
		rm -f /etc/config/old-wireless
	}

	#remove wlan from default bridge interface if there is no wifi hardware device
	[ -f /etc/config/wireless ] || {
		uci set network.lan.ifname="$(uci get network.lan.ifname | sed "s/wlan[0-9]//g")"
	}

	scan_hardwares

	apply_uci_config

	config_load system
	config_foreach system_config system

	killall -q hotplug2
	[ -x /sbin/hotplug2 ] && /sbin/hotplug2 --override --persistent \
			--set-rules-file /etc/hotplug2.rules \
			--set-coldplug-cmd /sbin/udevtrigger \
			--max-children 1 >/dev/null 2>&1 &

	# create /dev/root if it doesn't exist
	[ -e /dev/root -o -h /dev/root ] || {
		rootdev=$(awk 'BEGIN { RS=" "; FS="="; } $1 == "root" { print $2 }' < /proc/cmdline)
		[ -n "$rootdev" ] && ln -s "$rootdev" /dev/root
	}
    
}
