#!/bin/sh /etc/rc.common

. /lib/functions/partition.sh

START=40
STOP=98

system_config() {
	local cfg="$1"

	local hostname conloglevel

	config_get hostname "$cfg" hostname 'PulsarGateway'
	echo "$hostname" > /proc/sys/kernel/hostname

	config_get conloglevel "$cfg" conloglevel
	config_get buffersize "$cfg" buffersize
	[ -z "$conloglevel" -a -z "$buffersize" ] || dmesg ${conloglevel:+-n $conloglevel} ${buffersize:+-s $buffersize}

	config_get zonename "$cfg" zonename
	[ -n "$zonename" ] && [ -f "/usr/share/zoneinfo/$zonename" ] && ln -sf "/usr/share/zoneinfo/$zonename" /etc/localtime
}

apply_uci_config() {
	sh -c '. /lib/functions.sh; include /lib/config; uci_apply_defaults'
}

start() {
	apply_uci_config

	config_load system
	config_foreach system_config system

	return 0
}
