#!/bin/sh /etc/rc.common

START=40
STOP=98

start() {
	local NEED_COMMITS=false

        netif=`ip -o link  |awk -F: '{print $2}' | grep "^eth\|en" | sort`
	for i in $netif; do
		uci set network.wan.ifname=$i
		break
	done
	uci commit network	

	/sbin/wifi detect > /tmp/wireless.tmp
	if [ -s /tmp/wireless.tmp ]; then
		if [ ! -f /etc/config/wireless ]; then
			cat /tmp/wireless.tmp > /etc/config/wireless
			chmod 0600 /etc/config/wireless
		fi
	fi
	rm -f /tmp/wireless.tmp

	#remove wlan from default bridge interface if there is no wifi hardware device
	[ -f /etc/config/wireless ] || {
		uci set network.lan.ifname="$(uci get network.lan.ifname | sed "s/wlan[0-9]//g")"
		uci commit network
	}

	#update the device path/macaddr in case the /etc/conf/wireless
	#file is saved or copied from another target.
	#Please see also /lib/wifi/mac80211.sh in detail.
	[ -f /etc/config/wireless ] && {
		local dev_path old_path dev_mac old_mac

		if [ -x /usr/bin/readlink ] ; then
			old_path="$(uci -q get wireless.@wifi-device[0].path)"
			dev_path="$(readlink -f /sys/class/ieee80211/phy0/device)"
			dev_path="${dev_path##/sys/devices/}"
			[ "$dev_path" != "$old_path" ] && {
				NEED_COMMITS=true
				uci -q set  wireless.@wifi-device[0].path="$dev_path"
			}
		else
			old_mac="$(uci -q get wireless.@wifi-device[0].macaddr)"
			dev_mac="$(cat /sys/class/ieee80211/phy0/macaddress)"
			[ "$dev_mac" != "$old_mac" ] && {
				NEED_COMMITS=true
				uci -q set  wireless.@wifi-device[0].macaddr="$dev_mac"
			}
		fi
	}

	if $NEED_COMMITS ; then
		uci commit wireless
	fi

	return 0
}
