#!/bin/sh /etc/rc.common

. /lib/functions/partition.sh

START=40
STOP=98

system_config() {
	local cfg="$1"

	local hostname conloglevel

	config_get hostname "$cfg" hostname 'PulsarGateway'
	echo "$hostname" > /proc/sys/kernel/hostname

	config_get conloglevel "$cfg" conloglevel
	config_get buffersize "$cfg" buffersize
	[ -z "$conloglevel" -a -z "$buffersize" ] || dmesg ${conloglevel:+-n $conloglevel} ${buffersize:+-s $buffersize}

	config_get zonename "$cfg" zonename
	[ -n "$zonename" ] && [ -f "/usr/share/zoneinfo/$zonename" ] && ln -sf "/usr/share/zoneinfo/$zonename" /etc/localtime
}

apply_uci_config() {
	sh -c '. /lib/functions.sh; include /lib/config; uci_apply_defaults'
}

start() {
	apply_uci_config

	config_load system
	config_foreach system_config system

	killall -q hotplug2
	[ -x /sbin/hotplug2 ] && /sbin/hotplug2 --override --persistent \
			--set-rules-file /etc/hotplug2.rules \
			--set-coldplug-cmd /sbin/udevtrigger \
			--max-children 1 >/dev/null 2>&1 &

	# create /dev/root if it doesn't exist
	[ -e /dev/root -o -h /dev/root ] || {
		rootdev=$(awk 'BEGIN { RS=" "; FS="="; } $1 == "root" { print $2 }' < /proc/cmdline)
		[ -n "$rootdev" ] && ln -s "$rootdev" /dev/root
	}

	# Automatically mount boot partition to /boot/efi
	sys_mount_boot_partition

	# Automatically remount rootfs partition to /rootfs
	sys_remount_rootfs_partittion

	# bootonce validation as kernel upgrade work flow
	/sbin/gw_upgrade bootonce_install

	return 0
}
