#!/bin/sh /etc/rc.common

wait_netifd_ready() {
	/usr/bin/ubus -t 30 wait_for `/sbin/uci show network | sed '/=interface/!d;s/\(network\)\.\(.*\)=\(.*\)/\1.\3.\2/'`
	/bin/systemd-notify --ready --pid --status="Processing requests..."
}

start() {
	wait_netifd_ready &
	/sbin/netifd
}

stop() {
	/sbin/ifdown -a
	sleep 1

	killall netifd
}
